### ISSUE TITLE
Opencv Example, Inception model out of range error

### ISSUE THREAD

**Issue by stanleyoz** [google-coral/examples-camera#104]
### Description

Tks to Jonalla a few weeks back, we are able to start testing on the M.2 card in our IMX8 gateway. Just been benchmarking the opencv detect.py example. I could run the mobilenet with the coco_labels.txt. But when we changed the model to any of the inception models with the imagenet_labels.txt label file, we get a IndexError: list index out of range 

root@nodeG5:/google-coral/examples-camera/opencv# python detect.py --model ../all_models/inception_v4_299_quant_edgetpu.tflite --labels ../all_models/imagenet_labels.txt --camera_idx 2
Loading ../all_models/inception_v4_299_quant_edgetpu.tflite with ../all_models/imagenet_labels.txt labels.
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (961) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
Traceback (most recent call last):
  File "/google-coral/examples-camera/opencv/detectFPSTPU.py", line 117, in <module>
    main()
  File "/google-coral/examples-camera/opencv/detectFPSTPU.py", line 76, in main
    objs = get_objects(interpreter, args.threshold)[:args.top_k]
  File "/usr/lib/python3/dist-packages/pycoral/adapters/detect.py", line 214, in get_objects
    elif common.output_tensor(interpreter, 3).size == 1:
  File "/usr/lib/python3/dist-packages/pycoral/adapters/common.py", line 29, in output_tensor
    return interpreter.tensor(interpreter.get_output_details()[i]['index'])()
IndexError: list index out of range

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Linux

### Coral Device

M.2 Accelerator A+E

### Programming Language

Python 3.9

### Relevant Log Output

```shell
root@nodeG5:/google-coral/examples-camera/opencv# python detectFPSTPU.py --model ../all_models/inception_v4_299_quant_edgetpu.tflite --labels ../all_models/imagenet_labels.txt --camera_idx 2
Loading ../all_models/inception_v4_299_quant_edgetpu.tflite with ../all_models/imagenet_labels.txt labels.
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (961) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
Traceback (most recent call last):
  File "/google-coral/examples-camera/opencv/detectFPSTPU.py", line 117, in <module>
    main()
  File "/google-coral/examples-camera/opencv/detectFPSTPU.py", line 76, in main
    objs = get_objects(interpreter, args.threshold)[:args.top_k]
  File "/usr/lib/python3/dist-packages/pycoral/adapters/detect.py", line 214, in get_objects
    elif common.output_tensor(interpreter, 3).size == 1:
  File "/usr/lib/python3/dist-packages/pycoral/adapters/common.py", line 29, in output_tensor
    return interpreter.tensor(interpreter.get_output_details()[i]['index'])()
IndexError: list index out of range
```
</details>

**Comment by hjonnala** [comment]
> objs = get_objects(interpreter, args.threshold)[:args.top_k]

@stanleyoz please inspect the output parameters using https://netron.app/. If your model is different from the example models, you have to write own logic to parse the model output. Thanks!!

**Comment by stanleyoz** [comment]
I am just using the examples model/labels for detect.py script in your github, switching mobilenet/coco with available inception/imagenet just to check difference in performance. Is it not the compatible settings?

**Comment by stanleyoz** [comment]
python detect.py --model ../all_models/inception_v4_299_quant_edgetpu.tflite --labels ../all_models/imagenet_labels.txt --camera_idx 2 from available set of pre trained weights and labels

**Comment by hjonnala** [comment]
> I am just using the examples model/labels for detect.py script in your github, switching mobilenet/coco with available inception/imagenet just to check difference in performance. Is it not the compatible settings?

yes, the inception model you are using is for clasiifcation not for object detection..

inception model:
![image](https://github.com/google-coral/examples-camera/assets/86132058/6f0e398d-aaf2-4189-9b3e-a5131d9c265f)

mobilenet model:

![image](https://github.com/google-coral/examples-camera/assets/86132058/555dc4e4-a312-45e2-9854-4efbf1e67d8c)

**Comment by stanleyoz** [comment]
Yes .. now that make sense HHH. Sorry I am new to all ML frameworks & work-flow and esp. there are no many different packages etc (and I am an old school EEE guy) and tossing these in between tech-support calls and bug fixes. Do you know if it's worth testing/dev on YOLO at all on our IMX8 board with the Edge TPU for acceleration? We are moving towards packaging some ready "tools/demos" in our new industrial "smart" gateway to be launched in August. E.g. for PD, safety etc.

**Comment by hjonnala** [comment]
> Do you know if it's worth testing/dev on YOLO at all on our IMX8 board with the Edge TPU for acceleration? We are moving towards packaging some ready "tools/demos" in our new industrial "smart" gateway to be launched in August. E.g. for PD, safety etc.

I think, It depends on your available time and priorities.
