### ISSUE TITLE
opencv/install_requirements.sh error for RaspberryPi boards

### ISSUE THREAD

**Issue by rezgalis** [google-coral/examples-camera#13]
The install script tries to install OpenCV for Python3 using line
`  sudo apt install python3-opencv`

This gives an error that package is not found.

I am using Raspberry Pi 3B and with Raspbian Stretch (4.19.66-v7+)

**Comment by mtyka** [comment]
Looks like the python3-opencv package was added in Raspbian Buster. I recommend upgrading to that.  

Alternatively you can compile OpenCV for Raspberry Pi yourself, there are various tutorials on how to do that online, https://www.google.com/search?q=opencv+on+raspberry+pi
