### ISSUE TITLE
ImportError: No module named 'svgwrite'

### ISSUE THREAD

**Issue by ivenkwan** [google-coral/examples-camera#2]
pi@pi03:~/python-tflite-source/examples-camera/gstreamer $ python3 classify.pyTraceback (most recent call last):
  File "classify.py", line 19, in <module>
    import svgwrite
ImportError: No module named 'svgwrite'

is there any parm to specify my device be usb_cam

**Comment by mtyka** [comment]
Ah - you need to install svgwrite:

`pip3 install svgwrite `
