### ISSUE TITLE
view feed on Coral Dev Board

### ISSUE THREAD

**Issue by JVTEAM** [google-coral/examples-camera#3]
Given that the dev board has no visual desktop, how is this stream visible to the user?

**Comment by PeterMalkin** [comment]
You have two options:
1) Plug in a monitor through HDMI cable to get a visual desktop environment
`edgetpu_demo --device`

2) Use streaming mode to run the demo
`edgetpu_demo --stream`

More info: https://coral.withgoogle.com/docs/dev-board/get-started/#run-a-model-on-the-edge-tpu

**Comment by JVTEAM** [comment]
That runs the car demo.  It doesn't stream this particular script....

**Comment by PeterMalkin** [comment]
I am not sure what you are asking. But the code is open source. Feel free to modify it to make it do what your use case requires.

**Comment by JVTEAM** [comment]
That code doesn't play anything but the edgetpu demo.

**Comment by JVTEAM** [comment]
I'm trying to stream the classify.py etc.  The demo stream doesn't do that. Just the demo "car stream"
