### ISSUE TITLE
vidioc_streamon no space left on device

### ISSUE THREAD

**Issue by 12345k** [google-coral/examples-camera#32]
When I try to run the model by using  two webcams from USB hub I get this issue

VIDIOC_STREAMON: No space left on device
None
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /build/opencv-tragD2/opencv-3.2.0+dfsg/modules/imgproc/src/color.cpp, line 9748
Traceback (most recent call last):
  File "test1.py", line 14, in <module>
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
cv2.error: /build/opencv-tragD2/opencv-3.2.0+dfsg/modules/imgproc/src/color.cpp:9748: error: (-215) scn == 3 || scn == 4 in function cvtColor

Can you please suggest me a way to run multiple cameras feeds on google dev board

**Comment by Namburger** [comment]
@12345k seems like you are not the only one experiencing this issue, can you try out the the script I written [here](https://github.com/google-coral/edgetpu/issues/50#issuecomment-582971020) to see if the issue is still reproducible?

**Comment by mbrooksx** [comment]
Hi @12345k 

Here's a minimal gstreamer example: https://gist.github.com/mbrooksx/2bb6dfa1bdc74512688d7ffd588dc832

Note you need to install gstreamer1.0-tools

I have two versions in the script, one that takes raw frames at VGA resolution and one that has higher res which I then decode. I'm not sure how you're receiving frames in your version but I wouldn't expect hires raw frames to work.

Thanks,
Michael

**Comment by manoj7410** [comment]
@12345k Feel free to reopen if this is still an issue.
