### ISSUE TITLE
Running gstreamer example on jetson nano - internal data stream error

### ISSUE THREAD

**Issue by JVTEAM** [google-coral/examples-camera#35]
Error: gst-stream-error-quark: Internal data stream error. (1): gstbasesrc.c(3055): gst_base_src_loop (): /GstPipeline:pipeline0/GstV4l2Src:v4l2src0:
streaming stopped, reason not-negotiated (-4)

**Comment by hjonnala** [comment]
Unfortunately, gstreamer pipelines in this repo does not work with jetson nano.. Thanks!
