### ISSUE TITLE
RuntimeError Raspberry Pi

### ISSUE THREAD

**Issue by MichielBbal** [google-coral/examples-camera#39]
pi@raspberrypi:~/google-coral/examples-camera/raspicam $ python3 classify_captur                         e.py
Traceback (most recent call last):
  File "classify_capture.py", line 91, in <module>
    main()
  File "classify_capture.py", line 56, in main
    interpreter.allocate_tensors()
  File "/usr/local/lib/python3.7/dist-packages/tflite_runtime/interpreter.py", l                         ine 242, in allocate_tensors
    return self._interpreter.AllocateTensors()
  File "/usr/local/lib/python3.7/dist-packages/tflite_runtime/interpreter_wrappe                         r.py", line 115, in AllocateTensors
    return _interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
RuntimeError: Internal: Unsupported data type in custom op handler: 0Node number                          1 (EdgeTpuDelegateForCustomOp) failed to prepare.

**Comment by Namburger** [comment]
Can you share this command?
```
spkg -l | grep libedgetpu
```

**Comment by rcaudill** [comment]
I'm getting the same error on the Pi 4. Here is my output from the requested command:

> pi@raspberrypi:~/coral/examples-camera/raspicam $ dpkg -l | grep libedgetpu
ii  libedgetpu1-legacy-std:armhf         15.0                                armhf        Support library for Edge TPU

**Comment by Namburger** [comment]
@rcaudill please also make sure to upgrade your [tflite_runtime](https://www.tensorflow.org/lite/guide/python#install_just_the_tensorflow_lite_interpreter) package. it should be version 2.5.0 now!

**Comment by rcaudill** [comment]
@Namburger thanks for the quick response. It looks like 2.5 is installed. Does this look correct:

> $ python3 -c 'print(__import__("tflite_runtime").__version__)'
2.5.0

**Comment by Namburger** [comment]
@rcaudill ahhh, no problems! 
That looks okay, although I just realized that your libedgetpu is a legacy package (libedgetpu1-legacy-std:armhf 15.0), you should upgrade it!
```
$ sudo apt purge libedgetpu1-legacy-std
$ sudo apt install python3-pycoral
```
Verify that yo no longer have the legacy package (should looks like this now):
```
$ dpkg -l | grep edgetpu
ii  libedgetpu1-std:arm64                15.0                                arm64        Support library for Edge TPU
```

Lastly, sometimes linux wouldn't allows a certain usb rules by default so you may need this also:
```
$ sudo usermod -aG plugdev $USER
$ suo shutdown now
```

**Comment by rcaudill** [comment]
@Namburger updating libedgetpu fixed the problem. Thanks!
