### ISSUE TITLE
Segmentation Fault using gstreamer for both classify.py and detect.py

### ISSUE THREAD

**Issue by JSwaim22** [google-coral/examples-camera#41]
I am using a coral dev board and a coral camera. I followed the setup instructions and then ran python3 classify.py and python3 detect.py. Both ended up giving me a list of failures ending in a segmentation fault. I tried running them both while connected to a monitor and when not (I wasn't entirely clear on where the camera feed was supposed to show up).

I included pictures below. Any help would be greatly appreciated!

Thanks!

<img width="1216" alt="Screen Shot 2020-05-15 at 4 35 55 PM" src="https://user-images.githubusercontent.com/52038890/82094060-531a1580-96ca-11ea-8504-d035edc6cf61.png">
<img width="1216" alt="Screen Shot 2020-05-15 at 4 36 20 PM" src="https://user-images.githubusercontent.com/52038890/82094067-57463300-96ca-11ea-87b6-b38258b0c8d8.png">
<img width="1216" alt="Screen Shot 2020-05-15 at 4 36 59 PM" src="https://user-images.githubusercontent.com/52038890/82094074-5ad9ba00-96ca-11ea-8e3f-e39488b74edb.png">

**Comment by JSwaim22** [comment]
issue resolved

**Comment by alexanderfrey** [comment]
Having similar issue. Did you attach a monitor ? I thought the demo runs via stream...
```
python3 /home/mendel/google-coral/examples-camera/gstreamer/classify.py --videosrc /dev/video1
Unable to init server: Could not connect: Connection refused

(classify.py:6429): Gtk-WARNING **: 10:52:41.904: Locale not supported by C library.
	Using the fallback 'C' locale.
Unable to init server: Could not connect: Connection refused
Loading ../all_models/mobilenet_v2_1.0_224_quant_edgetpu.tflite with ../all_models/imagenet_labels.txt labels.
Detected Edge TPU dev board.
Gstreamer pipeline:
 v4l2src device=/dev/video1 ! video/x-raw,width=640,height=480,framerate=30/1 ! decodebin ! glupload ! tee name=t
            t. ! queue ! glfilterbin filter=glbox name=glbox ! video/x-raw,format=RGB,width=224,height=224 ! appsink name=appsink emit-signals=true max-buffers=1 drop=true
            t. ! queue ! glsvgoverlaysink name=overlaysink
        

(classify.py:6429): Gtk-CRITICAL **: 10:52:42.636: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(classify.py:6429): Gtk-CRITICAL **: 10:52:42.636: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(classify.py:6429): Gtk-CRITICAL **: 10:52:42.636: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed
Segmentation fault
```

**Comment by MTourabi** [comment]
Hello, i am having the same problem .Using the raspberry pi with pi camera and coral USB 
anyone can help please? thank you in advance
<img width="872" alt="erreur" src="https://user-images.githubusercontent.com/76753721/168618803-c5055b8c-957f-492b-83e3-1f5f3731ca1a.PNG">
