### ISSUE TITLE
Auto exposure control, auto white balance

### ISSUE THREAD

**Issue by laurentdebricon** [google-coral/examples-camera#51]
How to activate Auto exposure control, auto white balance of the google coral camera ?
https://coral.ai/products/camera/

> ISP Functions | Auto exposure control, auto white balance, auto band filter, auto 50/60Hz lumination, auto black level calibration

**Comment by hjonnala** [comment]
Hi, for changing/setting exposure and white balance, you may need to make modifications in the current driver code and rebuild the kernel image. Driver code can be found at:

https://coral.googlesource.com/linux-imx/+/refs/heads/master/drivers/media/platform/mxc/capture/ov5645_mipi_v2.c#2774

And instructions to build the kernel image can be seen at : https://coral.googlesource.com/docs/+/refs/heads/master/GettingStarted.md
