### ISSUE TITLE
Wrong video source in gstreamer

### ISSUE THREAD

**Issue by FranciZ** [google-coral/examples-camera#53]
If I read the documentation correctly the gstreamer.py video source [here](https://github.com/google-coral/examples-camera/blob/master/gstreamer/gstreamer.py#L207) should be `video0` to target the Coral camera?

**Comment by Namburger** [comment]
@FranciZ Yes, the dev board would use `/dev/video0`, but that's handled [here](https://github.com/google-coral/examples-camera/blob/master/gstreamer/detect.py#L119). That's default parameter which is only set if no arguments is being passed into it
