### ISSUE TITLE
Pygame detect and classify: SystemError: /dev/video16 is not a video capture device

### ISSUE THREAD

**Issue by FunkyGandalf** [google-coral/examples-camera#55]
Hello, I am having difficulty with the following error message when I try to run either detect.py or classify_capture.py through the pygame folder of the google coral examples-camera folder. I am using a USB webcam on Raspberry Pi 4.

pi@raspberrypi:~/coral/examples-camera/pygame $ python3 detect.py
pygame 1.9.4.post1
Hello from the pygame community. https://www.pygame.org/contribute.html
Loading ../all_models/mobilenet_ssd_v2_coco_quant_postprocess_edgetpu.tflite with ../all_models/coco_labels.txt labels.
By default using camera:  /dev/video16
Traceback (most recent call last):
  File "detect.py", line 154, in <module>
    main()
  File "detect.py", line 120, in main
    camera.start()
SystemError: /dev/video16 is not a video capture device

I am able to successfully run the opencv example without an issue so the installation and configuration seems to be correct.  I did run the pygame install requirements bash file and there are no errors.  There seems to be some difficulty with how the usb webcam is detected.

**Comment by Namburger** [comment]
@FunkyGandalf  
This is an opencv issue, basically trying to open `/dev/video16` to read inputs form the camera at [this line](https://github.com/google-coral/examples-camera/blob/master/opencv/detect.py#L94).
You can check which camera index is the correct one and run it using this:
```
python3 detect.py --camera_idx {idx}
```
