### ISSUE TITLE
support to stream RTSP ?

### ISSUE THREAD

**Issue by Ziegan** [google-coral/examples-camera#56]
Can Coral Dev board handle inferences on RTSP stream?

if yes can anyone help with it?

**Comment by Namburger** [comment]
@Ziegan Yes you can, quite easily by changing this line to take the rtsp source as argument:
https://github.com/google-coral/examples-camera/blob/master/opencv/detect.py#L94

**Comment by Ziegan** [comment]
Thanks ... Ill be sure to try it !

**Comment by jiekechoo** [comment]
python3 detect.py --videosrc "rtsp://192.168.120.58/ch01_sub.h264 ! rtph264depay ! h264parse ! avdec_h264 ! videoconvert"

it works for me.
