### ISSUE TITLE
Error using inat bird model with opencv detect.py

### ISSUE THREAD

**Issue by memmusty** [google-coral/examples-camera#57]
I'm trying to run the inat bird object detection model with opencv, I changed the model and labels files in `/home/pi/google-coral/examples-camera/opencv/detect.py` to mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite, inat_bird_labels.txt respectively. 

Please, note that I had done this with raspicam's classify_capture.py and it works fine.

When I run the open model on the CLI using the command 'python3 detect.py', I get the error
```
Traceback (most recent call last):
  File "detect.py", line 133, in <module>
    main()
  File "detect.py", line 109, in main
    objs = get_output(interpreter, score_threshold=args.threshold, top_k=args.top_k)
  File "detect.py", line 57, in get_output
    class_ids = common.output_tensor(interpreter, 1)
  File "/home/pi/google-coral/examples-camera/opencv/common.py", line 53, in output_tensor
    output_details = interpreter.get_output_details()[i]
IndexError: list index out of range
```
Any help on this issue?

**Comment by usbguru** [comment]
Hi Memmusty,
The model you selected, mobilenet_v2_1.0...  is a classification model, not a detection model:  https://aihub.cloud.google.com/p/products%2F5ea70ed9-9bd7-41e5-898f-e1509e8793bd

That's why that model works with the classify_capture.py code.

Try a mobilenet_ssd model for detection.
