### ISSUE TITLE
Unknown pixelformat

### ISSUE THREAD

**Issue by bricklane** [google-coral/examples-camera#59]
Trying to run detect.py on the coral dev board, using coral camera, and running into this issue continually.

`$ python3 detect.py`

`Loading ../all_models/mobilenet_ssd_v2_coco_quant_postprocess_edgetpu.tflite with ../all_models/coco_labels.txt labels.`

`[ 2440.991079] unknown pixelformat:'BGR3'`
`[ 2441.036095] mx6s-csi 30a90000.csi1_bridge: Fourcc format (0x33524742) invalid.`

`[ 2441.122862] unknown pixelformat:'YV12'`
`[ 2441.167939] mx6s-csi 30a90000.csi1_bridge: Fourcc format (0x32315659) invalid.`

`[ 2441.254807] unknown pixelformat:'411P'`
`[ 2441.299827] mx6s-csi 30a90000.csi1_bridge: Fourcc format (0x50313134) invalid.`

`[ 2441.386643] unknown pixelformat:'MJPG'`
`[ 2441.431718] mx6s-csi 30a90000.csi1_bridge: Fourcc format (0x47504a4d) invalid.`

`[ 2441.518516] unknown pixelformat:'JPEG'`
`[ 2441.563610] mx6s-csi 30a90000.csi1_bridge: Fourcc format (0x4745504a) invalid.`

`Unable to init server: Could not connect: Connection refused`

`(frame:4255): Gtk-WARNING **: 23:38:18.439: cannot open display:`

**Comment by Namburger** [comment]
@bricklane it is actually defaulted to [/dev/video0](https://github.com/google-coral/examples-camera/blob/master/gstreamer/detect.py#L119).
Although, this repo is being updated currently and won't works since our edgetpu API is deprecated for pycoral. We're actively working on updating this and will have it working soon. Apologies!

**Comment by bricklane** [comment]
Thanks for the info! To clarify, are you saying that using a usb camera and switching to /dev/video1 would be a solve in the meantime?

**Comment by Namburger** [comment]
Hello, no, unfortunately the issue is with the edgetpu API (the AI inference library) and not the video inputs :/

**Comment by Namburger** [comment]
Here is a quick detection srcipt if you want to use this in the meanwhile: https://gist.github.com/Namburger/f7e6c18af94ef3d6a70076a130eb1f7c

**Comment by Namburger** [comment]
But maybe you can use this detection script in the mean while?
https://gist.github.com/Namburger/f7e6c18af94ef3d6a70076a130eb1f7c

**Comment by bricklane** [comment]
That makes sense. I'll look into it - thanks!

**Comment by manoj7410** [comment]
Feel free to reopen if the issue still persists.
