### ISSUE TITLE
The nativeapp crashed when running with mobilenet_ssd_v2_coco_quant_postprocess_edgetpu.tflite

### ISSUE THREAD

**Issue by ting3000** [google-coral/examples-camera#70]
Build the nativeapp on Coral Dev Board, then running it with mobilenet_v2_1.0_224_quant_edgetpu.tflite successfully.
But running it with mobilenet_ssd_v2_coco_quant_postprocess_edgetpu.tflite, it crashed with "Segmentation fault".
Could somebody help! Thanks!

**Comment by Namburger** [comment]
hello @ting3000,
ssd mobilenet is a detection model, the native app only written to handles classification model outputs so that is expected.
You can follow this code to parse the outputs though: https://github.com/Namburger/edgetpu-detection-camera/blob/master/src/tflite_wrapper.cc#L96
