### ISSUE TITLE
Gtk-WARNING **: 02:43:47.869: cannot open display:

### ISSUE THREAD

**Issue by Tylersuard** [google-coral/examples-camera#71]
Running this command:

 edgetpu_classify \
> --source /dev/video1:YUY2:800x600:20/1 \
> --model ${DEMO_FILES}/mobilenet_v2_1.0_224_quant_edgetpu.tflite \

As per this tutorial:

https://coral.ai/docs/dev-board/camera/#try-other-example-code

The server version works fine, but when I try to use my monitor... I get the above error.

**Comment by Namburger** [comment]
is this on the dev board? Have you checked your USB camera config? 
Also you may try restarting the weston service:
```
$ sudo systemctl restart weston
```

**Comment by strubell** [comment]
Thanks! This worked for me to get the server version running.
