### ISSUE TITLE
How to record a video in coral dev board using hardware codec ?

### ISSUE THREAD

**Issue by vaibhav810** [google-coral/examples-camera#73]
I have coral dev kit and coral camera with me..

I want my inference pipelining running as it as while recording input (raw format is also acceptable ) camera frames in file parallely  .How do i achieve that ? gsteramer pipeline ? 

If i use cv2.videowriter , its very bottleneck & low fps

**Comment by manoj7410** [comment]
Responded at https://github.com/google-coral/pycoral/issues/20#issuecomment-791781536
