### ISSUE TITLE
Model performance difference between pygame and gstreamer.

### ISSUE THREAD

**Issue by SunBeenMoon** [google-coral/examples-camera#78]
Hi, 
I'm testing the examples-camera with Coral mini dev board. 

As shown in the figure below, the same task, the same model, performs differently on gstreamer and pygame examples (https://github.com/google-coral/examples-camera).

For example, 
in 'image classification' example, 
'mobilenet_v2_1.0_224_quant_edgetpu.tflite' model,
inference time of gstreamer is 19.46[ms], pygame is 16.00[ms]
fps of gstreamer is 30[fps], pygame is 10[fps]

![image](https://user-images.githubusercontent.com/78002830/119954435-ef634180-bfd9-11eb-842f-60eecd3e7967.png)
![image](https://user-images.githubusercontent.com/78002830/119954452-f427f580-bfd9-11eb-862e-2561dccd3b42.png)

I want to know why there is a difference in performance between pygame and gstreamer.

Regards,

**Comment by manoj7410** [comment]
As discussed over Skyvine, we cannot expect both pygame and gstreamer to perform exactly same. There will always be some difference among the performances of pygame, gstreamer and opencv.
