### ISSUE TITLE
Data Loss | Power Outage | Teachable machine

### ISSUE THREAD

**Issue by AlexHarrison1** [google-coral/examples-camera#81]
Dear Community,

I am trying to build an application of Teachable Machine using Coral's USB Accelerator & Pi for the visual inspection. Everything goes well when I train the offline model. However, that model was totally lost if there is a power outage and I have to retrain whole previous set. 

I wonder that is there any solutions for this issue to back up data? Can we use UPS (uninterruptible power supply) in this situation? Or on the other hand, can we retake the data in somehow? 

I am really looking for your help and advices to sort the issue out!
Alex.

**Comment by hjonnala** [comment]
Hi, Any training that takes more than couple of minutes is not recommended on coral edgetpu devices. The main purpose of the coral devices is to run the inferences. 

We recommend to opt out for cloud based solutions or server class machines for model training.
