### ISSUE TITLE
Focus Caral Camera

### ISSUE THREAD

**Issue by RaphaelPiatek** [google-coral/examples-camera#93]
### Description

Hi,
is there any way to focus the cam? so when running the classify Script the image is in focus?
Regards

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Mendel Linux

### Coral Device

Dev Board Mini, Coral Camera

### Programming Language

Python 3.7

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hello @RaphaelPiatek  Auto foucs is enabled by defualt for Coral Camera !!
